import AppShell from '@/layout/AppShell.vue'
import BusinessPageView from '@/views/business/BusinessPageView.vue'
import ScoreSummaryInteractiveView from '@/views/business/ScoreSummaryInteractiveView.vue'
import SelectionStudentInteractiveView from '@/views/business/SelectionStudentInteractiveView.vue'
import TaskbookApprovalInteractiveView from '@/views/business/TaskbookApprovalInteractiveView.vue'
import DashboardView from '@/views/dashboard/DashboardView.vue'
import ForbiddenView from '@/views/public/ForbiddenView.vue'
import LoginView from '@/views/public/LoginView.vue'
import NotFoundView from '@/views/public/NotFoundView.vue'
import RoleSelectView from '@/views/public/RoleSelectView.vue'
import TopicCreateInteractiveView from '@/views/business/TopicCreateInteractiveView.vue'
import TopicListInteractiveView from '@/views/business/TopicListInteractiveView.vue'
import NotificationsView from '@/views/workspace/NotificationsView.vue'
import ProfileView from '@/views/workspace/ProfileView.vue'

function createFeatureRoute({
  path,
  name,
  component = BusinessPageView,
  title,
  roles,
  permissionKey,
  navGroup,
  description,
  hidden = false,
}) {
  return {
    path,
    name,
    component,
    meta: {
      title,
      roles,
      permissionKey,
      navGroup,
      description,
      hidden,
    },
  }
}

export const featureRoutes = [
  {
    path: 'dashboard',
    name: 'dashboard',
    component: DashboardView,
    meta: {
      title: '首页仪表盘',
      roles: ['systemAdmin', 'teachingSecretary', 'collegeDean', 'majorLeader', 'supervisor', 'reviewTeacher', 'defenseRecorder', 'student'],
      permissionKey: 'dashboard:view',
      navGroup: '工作台',
      description: '展示当前角色的待办事项、流程进度和关键统计概览。',
    },
  },
  {
    path: 'profile',
    name: 'profile',
    component: ProfileView,
    meta: {
      title: '个人中心',
      roles: ['systemAdmin', 'teachingSecretary', 'collegeDean', 'majorLeader', 'supervisor', 'reviewTeacher', 'defenseRecorder', 'student'],
      permissionKey: 'user:profile',
      navGroup: '工作台',
      description: '维护个人信息、联系方式和常用设置。',
    },
  },
  {
    path: 'notifications',
    name: 'notifications',
    component: NotificationsView,
    meta: {
      title: '消息中心',
      roles: ['systemAdmin', 'teachingSecretary', 'collegeDean', 'majorLeader', 'supervisor', 'reviewTeacher', 'defenseRecorder', 'student'],
      permissionKey: 'notice:view',
      navGroup: '工作台',
      description: '集中查看系统通知、流程提醒和审批消息。',
    },
  },
  createFeatureRoute({
    path: 'topic/list',
    name: 'topic-list',
    component: TopicListInteractiveView,
    title: '课题列表',
    roles: ['systemAdmin', 'teachingSecretary', 'collegeDean', 'majorLeader', 'supervisor', 'student'],
    permissionKey: 'topic:view',
    navGroup: '课题与选题',
    description: '查看课题清单、申报状态和发布情况。',
  }),
  createFeatureRoute({
    path: 'topic/create',
    name: 'topic-create',
    component: TopicCreateInteractiveView,
    title: '课题申报',
    roles: ['supervisor', 'student'],
    permissionKey: 'topic:create',
    navGroup: '课题与选题',
    description: '提交课题申报信息并维护课题基础资料。',
  }),
  createFeatureRoute({
    path: 'topic/review',
    name: 'topic-review',
    title: '课题审核',
    roles: ['majorLeader', 'collegeDean'],
    permissionKey: 'topic:review',
    navGroup: '课题与选题',
    description: '对课题申报进行审核、退回和状态确认。',
  }),
  createFeatureRoute({
    path: 'topic/publish',
    name: 'topic-publish',
    title: '课题发布',
    roles: ['majorLeader', 'collegeDean'],
    permissionKey: 'topic:publish',
    navGroup: '课题与选题',
    description: '统一发布课题并控制学生可见范围。',
  }),
  createFeatureRoute({
    path: 'selection/student',
    name: 'selection-student',
    component: SelectionStudentInteractiveView,
    title: '学生选题',
    roles: ['student'],
    permissionKey: 'selection:student',
    navGroup: '课题与选题',
    description: '学生提交志愿、查看选题结果与确认状态。',
  }),
  createFeatureRoute({
    path: 'selection/confirm',
    name: 'selection-confirm',
    title: '教师确认',
    roles: ['supervisor'],
    permissionKey: 'selection:confirm',
    navGroup: '课题与选题',
    description: '指导教师确认学生选题并处理双选结果。',
  }),
  createFeatureRoute({
    path: 'selection/review',
    name: 'selection-review',
    title: '双选审核',
    roles: ['majorLeader'],
    permissionKey: 'selection:review',
    navGroup: '课题与选题',
    description: '审核双选结果并处理调剂、冲突与异常情况。',
  }),
  createFeatureRoute({
    path: 'taskbook/detail/:id',
    name: 'taskbook-detail',
    title: '任务书详情',
    roles: ['student', 'supervisor', 'majorLeader'],
    permissionKey: 'taskbook:detail',
    navGroup: '过程材料',
    description: '查看任务书详情、指导意见和审批状态。',
    hidden: true,
  }),
  createFeatureRoute({
    path: 'taskbook/approval',
    name: 'taskbook-approval',
    component: TaskbookApprovalInteractiveView,
    title: '任务书审批',
    roles: ['majorLeader'],
    permissionKey: 'taskbook:approval',
    navGroup: '过程材料',
    description: '审批任务书并反馈修改意见。',
  }),
  createFeatureRoute({
    path: 'proposal/submit',
    name: 'proposal-submit',
    title: '开题报告提交',
    roles: ['student'],
    permissionKey: 'proposal:submit',
    navGroup: '过程材料',
    description: '提交开题报告并查看审核进度。',
  }),
  createFeatureRoute({
    path: 'proposal/review',
    name: 'proposal-review',
    title: '开题报告审核',
    roles: ['supervisor', 'reviewTeacher'],
    permissionKey: 'proposal:review',
    navGroup: '过程材料',
    description: '填写评审意见并给出开题审核结论。',
  }),
  createFeatureRoute({
    path: 'midterm/submit',
    name: 'midterm-submit',
    title: '中期检查提交',
    roles: ['student'],
    permissionKey: 'midterm:submit',
    navGroup: '过程材料',
    description: '提交中期检查材料并查看反馈。',
  }),
  createFeatureRoute({
    path: 'midterm/review',
    name: 'midterm-review',
    title: '中期检查审核',
    roles: ['supervisor', 'reviewTeacher', 'majorLeader'],
    permissionKey: 'midterm:review',
    navGroup: '过程材料',
    description: '审核中期检查结果并记录阶段评价。',
  }),
  createFeatureRoute({
    path: 'paper/draft',
    name: 'paper-draft',
    title: '论文初稿提交',
    roles: ['student'],
    permissionKey: 'paper:draft',
    navGroup: '论文与评审',
    description: '上传论文初稿并查看指导反馈。',
  }),
  createFeatureRoute({
    path: 'paper/final',
    name: 'paper-final',
    title: '论文定稿提交',
    roles: ['student'],
    permissionKey: 'paper:final',
    navGroup: '论文与评审',
    description: '提交论文定稿、查重结果和附件材料。',
  }),
  createFeatureRoute({
    path: 'paper/review',
    name: 'paper-review',
    title: '论文审核',
    roles: ['supervisor'],
    permissionKey: 'paper:review',
    navGroup: '论文与评审',
    description: '审核论文状态、整改意见和最终提交情况。',
  }),
  createFeatureRoute({
    path: 'review/assign',
    name: 'review-assign',
    title: '评阅教师分配',
    roles: ['majorLeader'],
    permissionKey: 'review:assign',
    navGroup: '论文与评审',
    description: '为学生分配评阅教师并管理评阅进度。',
  }),
  createFeatureRoute({
    path: 'review/workspace',
    name: 'review-workspace',
    title: '评阅工作台',
    roles: ['reviewTeacher'],
    permissionKey: 'review:workspace',
    navGroup: '论文与评审',
    description: '评阅教师查看论文并录入评阅意见。',
  }),
  createFeatureRoute({
    path: 'defense/group',
    name: 'defense-group',
    title: '答辩分组管理',
    roles: ['majorLeader', 'defenseRecorder'],
    permissionKey: 'defense:group',
    navGroup: '答辩与成绩',
    description: '创建答辩分组、安排时间地点和答辩名单。',
  }),
  createFeatureRoute({
    path: 'defense/score-entry',
    name: 'defense-score-entry',
    title: '答辩成绩录入',
    roles: ['defenseRecorder'],
    permissionKey: 'defense:score-entry',
    navGroup: '答辩与成绩',
    description: '录入答辩评分、评语和答辩结论。',
  }),
  createFeatureRoute({
    path: 'score/summary',
    name: 'score-summary',
    component: ScoreSummaryInteractiveView,
    title: '成绩汇总',
    roles: ['teachingSecretary', 'majorLeader'],
    permissionKey: 'score:summary',
    navGroup: '答辩与成绩',
    description: '汇总指导、评阅、答辩成绩并生成总评。',
  }),
  createFeatureRoute({
    path: 'score/publish',
    name: 'score-publish',
    title: '成绩发布',
    roles: ['teachingSecretary'],
    permissionKey: 'score:publish',
    navGroup: '答辩与成绩',
    description: '审核并发布最终成绩。',
  }),
  createFeatureRoute({
    path: 'score/adjustment',
    name: 'score-adjustment',
    title: '成绩调整',
    roles: ['teachingSecretary', 'systemAdmin'],
    permissionKey: 'score:adjustment',
    navGroup: '答辩与成绩',
    description: '处理成绩修正、复核和特殊情况。',
  }),
  createFeatureRoute({
    path: 'statistics/progress',
    name: 'statistics-progress',
    title: '进度统计',
    roles: ['systemAdmin', 'teachingSecretary', 'collegeDean', 'majorLeader'],
    permissionKey: 'statistics:progress',
    navGroup: '统计与归档',
    description: '按角色、专业和阶段统计项目进度。',
  }),
  createFeatureRoute({
    path: 'statistics/topic',
    name: 'statistics-topic',
    title: '课题统计',
    roles: ['systemAdmin', 'teachingSecretary', 'collegeDean', 'majorLeader'],
    permissionKey: 'statistics:topic',
    navGroup: '统计与归档',
    description: '统计课题来源、审核通过率和选题情况。',
  }),
  createFeatureRoute({
    path: 'statistics/score',
    name: 'statistics-score',
    title: '成绩统计',
    roles: ['systemAdmin', 'teachingSecretary', 'collegeDean', 'majorLeader'],
    permissionKey: 'statistics:score',
    navGroup: '统计与归档',
    description: '统计成绩分布、优秀率和过程评价结构。',
  }),
  createFeatureRoute({
    path: 'archive/query',
    name: 'archive-query',
    title: '归档查询',
    roles: ['systemAdmin', 'teachingSecretary', 'collegeDean', 'majorLeader'],
    permissionKey: 'archive:query',
    navGroup: '统计与归档',
    description: '查询历届数据、过程材料和归档记录。',
  }),
  createFeatureRoute({
    path: 'archive/export',
    name: 'archive-export',
    title: '导出中心',
    roles: ['systemAdmin', 'teachingSecretary', 'collegeDean', 'majorLeader'],
    permissionKey: 'archive:export',
    navGroup: '统计与归档',
    description: '导出统计报表、学生材料和归档数据。',
  }),
  createFeatureRoute({
    path: 'system/users',
    name: 'system-users',
    title: '用户管理',
    roles: ['systemAdmin', 'teachingSecretary'],
    permissionKey: 'system:users',
    navGroup: '系统管理',
    description: '维护用户、角色和账号启停状态。',
  }),
  createFeatureRoute({
    path: 'system/org',
    name: 'system-org',
    title: '组织管理',
    roles: ['systemAdmin'],
    permissionKey: 'system:org',
    navGroup: '系统管理',
    description: '维护学院、专业、班级和组织结构信息。',
  }),
  createFeatureRoute({
    path: 'system/deadlines',
    name: 'system-deadlines',
    title: '时间节点设置',
    roles: ['systemAdmin', 'teachingSecretary'],
    permissionKey: 'system:deadlines',
    navGroup: '系统管理',
    description: '设置选题、开题、中期、答辩等时间节点。',
  }),
  createFeatureRoute({
    path: 'system/rules',
    name: 'system-rules',
    title: '评分规则设置',
    roles: ['systemAdmin'],
    permissionKey: 'system:rules',
    navGroup: '系统管理',
    description: '维护评分权重、评价指标和成绩规则。',
  }),
]

export const routes = [
  {
    path: '/login',
    name: 'login',
    component: LoginView,
    meta: {
      title: '登录',
      isPublic: true,
    },
  },
  {
    path: '/select-role',
    name: 'select-role',
    component: RoleSelectView,
    meta: {
      title: '角色切换',
      isPublic: true,
    },
  },
  {
    path: '/403',
    name: 'forbidden',
    component: ForbiddenView,
    meta: {
      title: '无权限访问',
      isPublic: true,
    },
  },
  {
    path: '/',
    component: AppShell,
    redirect: '/dashboard',
    children: featureRoutes,
  },
  {
    path: '/:pathMatch(.*)*',
    name: 'not-found',
    component: NotFoundView,
    meta: {
      title: '页面不存在',
      isPublic: true,
    },
  },
]
